<!DOCTYPE html>
<html>
<head>
    <title>BoxHop</title>
    <link rel="stylesheet" type="text/css" href="_css/bootstrap/bootstrap.css"/>
    <link rel="stylesheet" type="text/css" href="stylesheets/styles.css"/>
    <link rel="stylesheet" type="text/css" href="stylesheets/legal.css"/>

    <meta name="viewport" content="width=device-width, user-scalable=no"/>

    <?php include 'inc/header.inc'; ?>
</head>
<body>

<?php include 'inc/menu.inc'; ?>

<div id="legalDiv">
    <h1>EmYa Technologies LLC</h1>
    <h2>Privacy Policy</h2>
    <div class="row">
        <p><strong>Effective Date: May 1, 2014</strong><u></u></p>
        <p>This  Privacy Policy discloses the privacy practices for the www.boxhopp.com site and  the BoxHopp mobile application and various related services (together referred  to as the &quot;site&quot;). EmYa Technologies LLC, the provider of the site  (referred to as &quot;us&quot; or &quot;we&quot;), is committed to protecting  your privacy online. Please read the information below to learn the following  regarding your use of this site.</p>
        <p>You  acknowledge that this Privacy Policy is part of our Site Terms of Use, and by  accessing or using our site, you agree to be bound by all of its terms and  conditions. If you do not agree to these terms, please do not access or use  this site.</p>
        <p>We  reserve the right to change this Privacy Policy at any time. Such changes,  modifications, additions or deletions shall be effective immediately upon  notice thereof, which may be given by means including, but not limited to,  issuing an E-mail to the E-mail address listed by registered users and posting  the revised Policy on this page. You acknowledge and agree that it is your  responsibility to maintain a valid E-mail address as a registered user, review  this site and this Policy periodically and to be aware of any modifications. Your  continued use of the site after such modifications will constitute your: (a)  acknowledgment of the modified Policy; and (b) agreement to abide and be bound  by the modified Policy.</p>
        <p><strong> 1. Types  of Information Collected</strong></p>
        <p>In  order to better provide you with our numerous services, we collect two types of  information about our users: Personally Identifiable Information and  Non-Personally Identifiable Information. Our primary goal in collecting  information from you is to provide you with a smooth, efficient, and customized  experience while using our site.</p>
        <p><strong>In  compliance with the U.S. Children&rsquo;s Online Privacy Protection Act (COPPA), our  services and products arenot directed to users under 13 years of age  unless accessed under the careful supervision and consent of a parent or legal  guardian. Any use by someone under this age is strictly prohibited and will be  terminated immediately upon discovery. Further, any personally identifiable  information provided by someone under 13 or that identifies someone under this  age, will be deleted immediately upon discovery if in violation of this  restriction.</strong></p>
        <p>Personally  Identifiable Information: This refers to information that lets us know the  specifics of who you are. When you engage in certain activities on this site,  such as registering for a membership, ordering a product or service, submitting  content and/or posting content in discussion forums or other public areas,  entering a contest or sweepstakes, filling out a survey, or sending us  feedback, we may ask you to provide certain information about yourself by  filling out and submitting an online form. It is completely optional for you to  elect to engage in these activities, however, we may ask that you provide us  personal information, such as your first and last name, E-mail address, username,  password, gender, country of residence, and other personal identifying  information. Depending upon the activity, some of the information we ask you to  provide is identified as mandatory and some as voluntary. If you do not provide  the mandatory data with respect to a particular activity, you will not be able  to engage in that activity.</p>
        <p>Non-Personally  Identifiable Information: This refers to information that does not by itself  identify a specific individual. We gather certain information about you based  upon where you visit on our site in several ways. This information is compiled  and analyzed on both a personal and an aggregated basis. This information may  include the Web site's Uniform Resource Locator (&quot;URL&quot;) that you just  came from, which URL you next go to, what browser you are using, and your  Internet Protocol (&quot;IP&quot;) address. A URL is the global address of  documents and other resources on the World Wide Web. An IP address is an  identifier for a computer or device on a Transmission Control Protocol/Internet  Protocol (&quot;TCP/IP&quot;) network, such as the World Wide Web. Networks  like the Web use the TCP/IP protocol to route information based on the IP  address of the destination. In other words, an IP address is a number that is  automatically assigned to your computer whenever you are surfing the web,  allowing web servers to locate and identify your computer. Computers require IP  addresses in order for users to communicate on the Internet.</p>
        <p><strong>2.Collection  Methods and Use of Information</strong></p>
        <p>We do  not collect any Personally Identifiable Information about you unless you  voluntarily provide it to us. You provide certain Personally Identifiable  Information to us when you (a) register for our services and register your  E-mail address with us; or (b) send E-mail messages, submit forms or transmit  other information by telephone or letter. We may also collect information from  you at other points on our site that state that such information is being  collected.</p>
        <p>We  will primarily use your Personally Identifiable Information to provide our  services to you, as required by our agreements with you. We will also use  Personally Identifiable Information to enhance the operation of our site, fill  orders, improve our marketing and promotional efforts, statistically analyze  site use, improve our product and service offerings, and customize our site's  content, layout, and services. We may use Personally Identifiable Information  to deliver information to you and to contact you regarding administrative  notices. We may also use Personally Identifiable Information to resolve  disputes, troubleshoot problems and enforce our agreements with you, including  our Site Terms of Use, and this Privacy Policy.</p>
        <p><strong>3.Release  of Information</strong></p>
        <p>We do  not sell, trade, or rent your Personally Identifiable Information to others. Occasionally  we may be required by law enforcement or judicial authorities to provide  Personally Identifiable Information to the appropriate governmental  authorities. We will disclose Personally Identifiable Information upon receipt  of a court order, subpoena, or to cooperate with a law enforcement  investigation. We fully cooperate with law enforcement agencies in identifying  those who use our services for illegal activities. We reserve the right to  report to law enforcement agencies any activities that we in good faith believe  to be unlawful.</p>
        <p><strong>4.Updating  and Correcting Information</strong></p>
        <p>We  believe you should have the ability to access and edit the Personally Identifiable  Information that you have provided to us. You may change any of your Personally  Identifiable Information in your account online at any time through the site by  clicking &ldquo;Edit Profile&rdquo; from the &ldquo;Settings&rdquo; menu. You may also access and  correct your personal information and privacy preferences by writing us at  boxhoppteam@boxhopp.com.</p>
        <p>Please  send the email from your email address connected with your account and include  your name, username, E-mail address, and any requested changes when you contact  us.</p>
        <p>We  encourage you to promptly update your Personally Identifiable Information if it  changes. You may ask to have the information on your account deleted or  removed; however, because we keep track of past transactions, you cannot delete  information associated with past transactions on this site. In addition, it may  be impossible to completely delete your information without some residual  information because of backups.</p>
        <p><strong>5.User  Choices on Collection and Use of Information</strong></p>
        <p>We  may, from time to time, send you E-mail regarding services, namely, information  about popular reviews in your area, instructions on various ways to post video  reviews, or information on internal promotions.</p>
        <p>You  also have choices with respect to cookies, as described below. By modifying  your browser preferences, you have the choice to accept all cookies, to be  notified when a cookie is set, or to reject all cookies. If you choose to  reject all cookies some parts of our site may not work properly in your case.</p>
        <p><strong>6. Security  of Information</strong></p>
        <p>At  our site you can be assured that your Personally Identifiable Information is  secure, consistent with current industry standards. The importance of security  for all Personally Identifiable Information associated with our users is of  utmost concern to us. Your Personally Identifiable Information is protected in  several ways. Access by you to your Personally Identifiable Information is  available through a password and unique customer ID selected by you. This  password is encrypted. We recommend that you do not divulge your password to  anyone. In addition, your Personally Identifiable Information resides on a  secure server that only selected EmYa Technologies LLC personnel and  contractors have access to via password. We encrypt your Personally Identifiable  Information and thereby prevent unauthorized parties from viewing such  information when it is transmitted to us.</p>
        <p>Personal  information that you provide that is not Personally Identifiable Information  also resides on a secure server and is only accessible via password. Since this  information is not accessible from outside EmYa Technologies LLC you will not  be asked to select a password in order to view or modify such information.</p>
        <p>Unfortunately,  no data transmission over the Internet or any wireless network can be  guaranteed to be 100% secure. As a result, while we strive to protect your  Personally Identifiable Information, you acknowledge that: (a) there are  security and privacy limitations of the Internet which are beyond our control;  (b) the security, integrity and privacy of any and all information and data  exchanged between you and us through this site cannot be guaranteed; and (c)  any such information and data may be viewed or tampered with in transit by a  third party.</p>
        <p>&nbsp;</p>
        <p><strong>7. Cookies</strong></p>
        <p>When  you use our site we will store cookies on your computer in order to facilitate  and customize your use of our site. A cookie is a small data text file, which a  Web site stores on your computer's hard drive (if your Web browser permits)  that can later be retrieved to identify you to us. Our cookies store randomly  assigned user identification numbers, the country where you are located, and  your first name to welcome you back to our site. The cookies make your use of  the site easier, make the site run more smoothly and help us to maintain a  secure site. You are always free to decline our cookies if your browser  permits, but some parts of our site may not work properly in that case.</p>
        <p><strong>8. Google Analytics </strong></p>
        <p>Google Analytics is a program used to track visitors to this  Site, and it primarily helps measure how users interact with the Site content.  Google Analytics stores information about what pages you visit, how long you  are on the Site, how you got here and what links you click on. This analytics  data is collected via a JavaScript tag in the pages of this Site and is not  tied in any way to any Personally Identifiable Information. </p>
        <p>The information generated about your use of the Site  including your IP address is transmitted to Google. The information is then  used to evaluate visitor interactions with this Site and to compile reports on  website traffic activity for www.boxhopp.com. Neither EmYa Technologies LLC nor  Google will ever link or seek to link Personally Identifiable Information  provided by you to the Site to the data collected by Google Analytics.</p>
        <p>If  you would like to opt out of Google Analytics, Google has developed a tool that  works with major internet browsers to permit you to opt-out. For more  information and to install their opt-out tool, please click here: <a href="https://tools.google.com/dlpage/gaoptout">https://tools.google.com/dlpage/gaoptout</a>.</p>
        <p><strong>9. Privacy  Policies of Third Party Sites</strong></p>
        <p>Except  as otherwise discussed in this Privacy Policy, this document only addresses the  use and disclosure of information we collect from you. Other sites accessible  through our site have their own privacy policies and data collection, use and  disclosure practices. Please consult each site's privacy policy. We are not  responsible for the policies or practices of third parties.</p>
        <p><strong>10. Miscellaneous  Privacy Issues</strong></p>
        <p>You  must be at least 13 years old to have our permission to use this application.  If you are over the age of 13 but under the age of 18, you must have parental  permission to use this application. Our policy is that we do not knowingly  collect, use or disclose Personally Identifiable Information about visitors  that are under 13 years of age.</p>
        <p>At www.boxhopp.com,  we <strong>DO NOT</strong> respond to Do Not Track  signals.</p>
        <p>You  should also be aware that when Personally Identifiable Information is  voluntarily disclosed (i.e. your name, E-mail address, etc.) in the video  reviews, review comment area, user profiles or other public areas on this site,  that information, along with any information disclosed in your communication,  can be collected and used by third parties and may result in unsolicited  messages from third parties. Such activities are beyond our control and this  Policy does not apply to such information. Any submissions to video reviews,  review comment area, user profiles, or other public areas on this site are  accepted with the understanding that they are accessible to all third parties. If  you do not want your comments to be viewed by third parties, you are advised  not to make any submissions. Ultimately, you are solely responsible for  maintaining the secrecy of your password and/or account information. Please be  careful and responsible whenever you're online.</p>
        <p>If  you have any questions about this Privacy Policy, the practices of this site,  or your dealings with this site, please contact us by sending a message to boxhoppteam@boxhopp.com.</p>
    </div>
</div>

<?php include 'inc/footer.inc'; ?>

<script src="_js/jquery/jquery.js"></script>
<script src="_js/jquery-ui/jquery-ui.js"></script>
<script src="_js/jquery-waypoints/waypoints.js"></script>
<script src="_js/validatejs/validate.js"></script>
<script src="js/jumpSlides.js"></script>
<script src="js/scripts.js"></script>
</body>