<!DOCTYPE html>
<html>
<head>
    <title>BoxHop</title>
    <link rel="stylesheet" type="text/css" href="_css/bootstrap/bootstrap.css"/>
    <link rel="stylesheet" type="text/css" href="stylesheets/styles.css"/>
    <link rel="stylesheet" type="text/css" href="stylesheets/legal.css"/>

    <meta name="viewport" content="width=device-width, user-scalable=no"/>

    <?php include 'inc/header.inc'; ?>
</head>
<body>

<?php include 'inc/menu.inc'; ?>

<div id="legalDiv">
    <h1>EmYa Technologies LLC</h1>
    <h2>Privacy Policy</h2>
    <div class="row">
        <p><strong>1.User's  Acknowledgment and Acceptance of Terms</strong></p>
        <p>EmYa  Technologies, LLC (referred to as &quot;us&quot; or &quot;we&quot;) provides  the <a href="http://www.boxhopp.com">www.boxhopp.com</a> site and various  related services (together referred to  as this &quot;site&quot;), the Service and the Application subject to your  compliance with all the terms, conditions, and notices contained or referenced  herein (the &quot;Terms of Use&quot;), as well as any other written agreement  between us (or your company). In  addition, when using particular services or materials on this site, users shall  be subject to any posted guidelines or rules applicable to such services or materials  that may contain terms and conditions in addition to those in these Terms of  Use. All such guidelines or rules are  hereby incorporated by reference into these Terms of Use.</p>
        <p>BY  COMPLETING THE REGISTRATION PROCESS AND/OR USING THIS SITE, YOU AGREE TO BE  BOUND BY THESE TERMS OF USE. IF YOU DO  NOT WISH TO BE BOUND BY THE THESE TERMS OF USE, PLEASE EXIT THE SITE NOW. YOUR REMEDY FOR DISSATISFACTION WITH THIS  SITE, OR ANY PRODUCTS, SERVICES, CONTENT, OR OTHER INFORMATION AVAILABLE ON OR  THROUGH THIS SITE, IS TO STOP USING THE SITE AND/OR THOSE PARTICULAR PRODUCTS  OR SERVICES. YOUR AGREEMENT WITH US  REGARDING COMPLIANCE WITH THESE TERMS OF USE BECOMES EFFECTIVE IMMEDIATELY UPON  COMMENCEMENT OF YOUR USE OF THIS SITE.</p>
        <p>These  Terms of Use are effective as of May 1, 2014.  We reserve the right to change these Terms of Use from time to time  without notice to you. You acknowledge  and agree that it is your responsibility to review this site and these Terms of  Use periodically and to be aware of any modifications. Your continued use of this site after such  modifications will constitute your acknowledgment of the modified Terms of Use  and agreement to abide and be bound by the modified Terms of Use.</p>
        <p>As  used in these Terms of Use, references to our &quot;Affiliates&quot; include  our owners, subsidiaries, affiliated companies, officers, directors, suppliers,  partners, sponsors, and advertisers, and includes (without limitation) all  parties involved in creating, producing, and/or delivering this site and/or its  contents.</p>
        <p><strong>2.Description  of Services</strong></p>
        <p>We  make various services available on this site including, but not limited to, a  reverse online auction services with a focus on the moving industry. Customers  can post jobs or Requests for Quotes to BoxHopp.com or to the BoxHopp  application supplied by EmYa Technologies LLC that can be downloaded and  installed by Customers on their mobile phones. The Requests for Quotes are directed  to specific service companies who can fulfill the proposed job. Fees for the various services are set out in  the membership and service fees described elsewhere in this site. You are solely responsible for providing, at  your own expense, all equipment necessary to use the services, including a  device to access the Internet and your own Internet access (including payment  of telephone service fees associated with such access).</p>
        <p>We  reserve the sole right to either modify or discontinue the site, including any  features therein, at any time with or without notice to you. We shall not be liable to you or any third  party should we exercise such right.  Modifications may include, but are not limited to, changes in the  pricing structure, the addition of fee-based services, or changes to  limitations on allowable file sizes. Any  new features that augment or enhance the then-current services on this site  shall also be subject to these Terms of Use.</p>
        <p>You  understand and agree that temporary interruptions of the services available  through this site may occur as normal events.  You further understand and agree that we have no control over third  party networks you may access in the course of the use of this site, and  therefore, delays and disruption of other network transmissions are completely  beyond our control.</p>
        <p>You  understand and agree that the services available on this site are provided  &quot;AS IS&quot; and that we assume no responsibility for the timeliness,  deletion, mis-delivery or failure to store any user communications or  personalization settings.</p>
        <p><strong>3.The  Bid Process</strong><br />
            BoxHopp.com,  uses a distinct and novel platform for requesting bids from a Service Providers  that provide moving services to fulfill requirements for individual projects. BoxHopp  looks to identify user needs and connect the users with competitive Service Provider  bids. <br />
            Operator  will create an account with BoxHopp through an existing Google+ or Facebook  account in order to begin submitting Requests for Quotes (RFQ). Personally identifiable information regarding  the Operator&rsquo;s business will remain private until such time as Operator select Service  Providers to communicate with. However,  the Operator must enter an adequate amount of information regarding each  project in order to give Service Providers an adequate amount of detail so a  Service Provide may submit an accurate bid.&nbsp;An Operator may additionally  submit pictures, videos, and text descriptions of the items that need to be  moved.&nbsp; Once an Operator&rsquo;s RFQ is submitted, the RFQ will be sent to  multiple Service Providers that are able to fulfill the request based on the  account information supplied to BoxHopp. The service costs $3.99 to Operators  and the Operator&rsquo;s contact information will remain private until it has found a  suitable bid. <br />
            Service  Providers will also create an account with BoxHopp and specify the services  they can provide. That account will be  accessible to the Operators. When an Operator submits a RFQ, the job and the  pertinent information will be sent to the Service Provider in order for it to review  and consider submitting a bid for that job. There is a monthly cost to the Service  Provider to have a BoxHopp account and there is no cost to view RFQ&rsquo;s.&nbsp;However,  Service Providers may pay for additional features on top of the monthly fee. Service  Providers can review the parameters of each job with no obligation to place a bid.  Once a bid is placed by a Service  Provider, the RFQ information will show up on the Service Provider&rsquo;s and the Operator&rsquo;s  dashboard. The Operator will alert the  winning bidder. If a Service Provider&rsquo;s bid  is not accepted it will be alerted of the job closure. Operators have full discretion as to which  bids they select and there are no specific criteria requiring the Operator to  select a bid, including but not limited to, price, feedback, reputation, etc. </p>
        <p>The  acceptance of a bid by an Operator on our site does not constitute a binding  contract between the Operator and the Service Provider. Our site is used to  facilitate the initial relationship between the parties. Based on the volatility of the market, bids  and asking prices are subject to change within a short time frame. All final negotiations and bids will be  handled by the parties separately from the BoxHopp website, and nothing in this  agreement or on the website should be construed as a binding contract between Service  Providers and Operators. </p>
        <p><strong>4.Registration  Data and Privacy</strong></p>
        <p>In  order to access some of the services on this site, our site may require that  you have an existing Google + account, Facebook account, or a separate account  and password that can be obtained by completing our online registration form,  which requests certain information and data (&quot;Registration Data&quot;) and  maintaining and updating your Registration Data as required. By registering, you agree that all  information provided in the Registration Data is true and accurate and that you  will maintain and update this information as required in order to keep it  current, complete and accurate.</p>
        <p>You  also grant us the right to disclose to third parties certain Registration Data  about you. The information we obtain  through your use of this site, including your Registration Data, is subject to  our Privacy Policy, which is specifically incorporated by reference into these  Terms of Use.</p>
        <p><strong>5.Payment  of Fees</strong></p>
        <p>If  you subscribe to a service on this site that requires payment of a fee, you  agree to pay all fees associated with such service. For all charges for services on this site, we  will bill you through Google Wallet, Paypal, or credit card. Recurring charges are billed in advance of  service. You agree to provide us with  accurate and complete billing information, including valid credit card  information, your name, address and telephone number, and to provide us with  any changes in such information within five business (5) days of the change.</p>
        <p>If,  for any reason, Google Wallet, Papal, or your credit card company refuses to  pay the amount billed for the service, you agree that we may, at our option,  suspend or terminate your subscription to the service and require you to pay  the overdue amount by other means acceptable to us. We may charge a fee for reinstatement of  suspended or terminated accounts.</p>
        <p>In  the event legal action is necessary to collect on balances due, you agree to  reimburse us for all expenses incurred to recover sums due, including attorney  fees and other legal expenses.</p>
        <p>In  the event of termination of the website, customers should contact us at <a href="mailto:Boxhoppteam@boxhopp.com">Boxhoppteam@boxhopp.com</a>, if you have  a remaining balance in your account. </p>
        <p>&nbsp;</p>
        <p><strong>6.Conduct  on Site</strong></p>
        <p>Your  use of the site is subject to all applicable laws and regulations, including Netiquette  and you are solely responsible for the contents of your communications through  the site. By posting information in or  otherwise using any communications service, chat room, message board,  newsgroup, software library, or other interactive service that may be available  to you on or through this site, you agree that you will not upload, share,  post, or otherwise distribute or facilitate distribution of any content -- including  text, communications, software, images, sounds, data, or other information --  that:</p>
        <p>(a)Is  unlawful, threatening, abusive, harassing, defamatory, libelous, deceptive,  fraudulent, invasive of another's privacy, tortious, contains explicit or graphic  descriptions or accounts of sexual acts (including but not limited to sexual  language of a violent or threatening nature directed at another individual or  group of individuals), or otherwise violates our rules or policies;</p>
        <p>(b)Victimizes,  harasses, degrades, or intimidates an individual or group of individuals on the  basis of religion, gender, sexual orientation, race, ethnicity, age, or  disability;</p>
        <p>(c)Infringes  on any patent, trademark, trade secret, copyright, right of publicity, or other  proprietary right of any party;</p>
        <p>(d)Constitutes  unauthorized or unsolicited advertising, junk or bulk e-mail (also known as  &quot;spamming&quot;), chain letters, any other form of unauthorized  solicitation, or any form of lottery or gambling;</p>
        <p>(e)Contains  software viruses or any other computer code, files, or programs that are  designed or intended to disrupt, damage, or limit the functioning of any  software, hardware, or telecommunications equipment or to damage or obtain  unauthorized access to any data or other information of any third party; or</p>
        <p>(f)Impersonates  any person or entity, including any of our employees or representatives.</p>
        <p>We  neither endorse nor assume any liability for the contents of any material  uploaded or submitted by third party users of the site. We generally do not pre-screen, monitor, or  edit the content posted by users of communications services, chat rooms,  message boards, newsgroups, software libraries, or other interactive services  that may be available on or through this site.  However, we and our agents have the right at their sole discretion to  remove any content that, in our judgment, does not comply with these Terms of  Use and any other rules of user conduct for our site, or is otherwise harmful,  objectionable, or inaccurate. We are not  responsible for any failure or delay in removing such content. You hereby consent to such removal and waive  any claim against us arising out of such removal of content. See &quot;Use of Your Materials&quot; below  for a description of the procedures to be followed in the event that any party  believes that content posted on this site infringes on any patent, trademark,  trade secret, copyright, right of publicity, or other proprietary right of any  party.</p>
        <p>In  addition, you may not use your account to breach security of another account or  attempt to gain unauthorized access to another network or server. Not all areas of the site may be available to  you or other authorized users of the site.  You shall not interfere with anyone else's use and enjoyment of the site  or other similar services. Users who  violate systems or network security may incur criminal or civil liability.</p>
        <p>You  agree that we may at any time, and at our sole discretion, terminate your  membership without prior notice to you for violating any of the above provisions. In addition, you acknowledge that we will  cooperate fully with investigations of violations of systems or network  security at other sites, including cooperating with law enforcement authorities  in investigating suspected criminal violations.</p>
        <p><strong>7.Third  Party Sites and Information</strong></p>
        <p>This  site may link you to other sites on the Internet or otherwise include  references to information, documents, software, materials and/or services  provided by other parties. These sites  may contain information or material that some people may find inappropriate or  offensive. These other sites and parties  are not under our control, and you acknowledge that we are not responsible for  the accuracy, copyright compliance, legality, decency, or any other aspect of  the content of such sites, nor are we responsible for errors or omissions in  any references to other parties or their products and services. The inclusion of such a link or reference is  provided merely as a convenience and does not imply endorsement of, or  association with, the site or party by us, or any warranty of any kind, either  express or implied.</p>
        <p><strong>8.Intellectual  Property Information</strong></p>
        <p>Copyright  © 2014, EmYa Technologies LLC, All Rights Reserved.</p>
        <p>For  purposes of these Terms of Use, &quot;content&quot; is defined as any information,  communications, software, photos, video, graphics, music, sounds, and other  material and services that can be viewed by users on our site. This includes, but is in no way limited to,  message boards, chat, and other original content.</p>
        <p>By  accepting these Terms of Use, you acknowledge and agree that all content  presented to you on this site is protected by copyrights, trademarks, service  marks, patents or other proprietary rights and laws, and is the sole property  of EmYa Technologies LLC and/or its Affiliates.  You are only permitted to use the content as expressly authorized by us  or the specific content provider. Except  for a single copy made for personal use only, you may not copy, reproduce,  modify, republish, upload, post, transmit, or distribute any documents or  information from this site in any form or by any means without prior written  permission from us or the specific content provider, and you are solely  responsible for obtaining permission before reusing any copyrighted material  that is available on this site. Any  unauthorized use of the materials appearing on this site may violate copyright,  trademark and other applicable laws and could result in criminal or civil  penalties.</p>
        <p>Neither  we or our Affiliates warrant or represent that your use of materials displayed  on, or obtained through, this site will not infringe the rights of third  parties. See &quot;Use of Your  Materials&quot; below for a description of the procedures to be followed in the  event that any party believes that content posted on this site infringes on any  patent, trademark, trade secret, copyright, right of publicity, or other  proprietary right of any party.</p>
        <p>The  following are registered trademarks, trademarks or service marks of EmYa  Technologies LLC or its Affiliates. All  custom graphics, icons, logos and service names are registered trademarks,  trademarks or service marks of EmYa Technologies LLC or its Affiliates. All other trademarks or service marks are  property of their respective owners.  Nothing in these Terms of Use grants you any right to use any trademark,  service mark, logo, and/or the name of EmYa Technologies LLC or its Affiliates.</p>
        <p><strong>9.User's  Materials</strong></p>
        <p>Subject  to our Privacy Policy, any communication or material that you transmit to this  site or to us, whether by electronic mail or other means, for any reason, will  be treated as non-confidential and non-proprietary. While you retain all rights in such  communications or material, you grant us and our designated licensees a non-exclusive,  paid-up, perpetual, and worldwide right to copy, distribute, display, perform,  publish, translate, adapt, modify, and otherwise use such material for any  purpose regardless of the form or medium (now known or not currently known) in  which it is used.</p>
        <p>Please  do not submit confidential or proprietary information to us unless we have  mutually agreed in writing otherwise. We  are also unable to accept your unsolicited ideas or proposals, so please do not  submit them to us in any circumstance.</p>
        <p>We  respect the intellectual property of others, and we ask you to do the  same. If you or any user of this site  believes its copyright, trademark or other property rights have been infringed  by a posting on this site, you or the user should send notification to our  Designated Agent (as identified below) immediately. To be effective, the notification must  include:</p>
        <p>(a)A physical  or electronic signature of a person authorized to act on behalf of the owner of  an exclusive right that is allegedly infringed'</p>
        <p>(b)Identification  of the copyrighted work claimed to have been infringed;</p>
        <p>(c)Information  reasonably sufficient to permit us to contact the complaining party, such as  address, telephone number and, if available, an electronic mail address at  which the complaining party may be contacted;</p>
        <p>(d)Identification  of the material that is claimed to be infringing or to be subject to infringing  activity and that is to be removed and information reasonably sufficient to  permit us to locate the materials;</p>
        <p>(e)A  statement that the complaining party has a good faith belief that use of the  material in the manner complained of is not authorized by the copyright owner,  agent, or the law; and</p>
        <p>(f)A  statement that the information in the notification is accurate and, under  penalty of perjury, that the complaining party is authorized to act on behalf  of the owner of an exclusive right that is allegedly infringing.</p>
        <p>Pursuant  to the Digital Millennium Copyright Act, 17 U.S.C. Sec. 512(c), our Designated  Agent for Notice of claims of copyright infringement can be reached as  indicated below. Service of repeat  infringers of copyright or of users about whom repeat claims of copyright  infringement are received will be terminated.</p>
        <p>Customer  Service: <a href="mailto:Boxhoppteam@boxhopp.com">Boxhoppteam@boxhopp.com</a></p>
        <p>Designated  Agent for Claimed Infringement:</p>
        <p>Customer  Service<br />
            12370  Alameda Trace Circle,<br />
            Unit  1124<br />
            Austin  78727</p>
        <p>Your  acknowledge and agree that upon receipt of a notice of a claim of copyright  infringement, we may immediately remove the identified materials from our site  without liability to you or any other party and that the claims of the  complaining party and the party that originally posted the materials will be  referred to the United States Copyright Office for adjudication as provided in  the Digital Millennium Copyright Act.</p>
        <p><strong>10.Disclaimer  of Warranties</strong></p>
        <p>ALL  MATERIALS AND SERVICES ON THIS SITE ARE PROVIDED ON AN &quot;AS IS&quot; AND  &quot;AS AVAILABLE&quot; BASIS WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESS OR  IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF  MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR THE WARRANTY OF  NON-INFRINGEMENT. WITHOUT LIMITING THE  FOREGOING, WE MAKE NO WARRANTY THAT (a) THE SERVICES AND MATERIALS WILL MEET  YOUR REQUIREMENTS, (b) THE SERVICES AND MATERIALS WILL BE UNINTERRUPTED,  TIMELY, SECURE, OR ERROR-FREE, (c) THE RESULTS THAT MAY BE OBTAINED FROM THE  USE OF THE SERVICES OR MATERIALS WILL BE EFFECTIVE, ACCURATE OR RELIABLE, OR  (d) THE QUALITY OF ANY PRODUCTS, SERVICES, OR INFORMATION PURCHASED OR OBTAINED  BY YOU FROM THE SITE FROM US OR OUR AFFILIATES WILL MEET YOUR EXPECTATIONS OR  BE FREE FROM MISTAKES, ERRORS OR DEFECTS.</p>
        <p>THIS  SITE COULD INCLUDE TECHNICAL OR OTHER MISTAKES, INACCURACIES OR TYPOGRAPHICAL  ERRORS. WE MAY MAKE CHANGES TO THE  MATERIALS AND SERVICES AT THIS SITE, INCLUDING THE PRICES AND DESCRIPTIONS OF  ANY PRODUCTS LISTED HEREIN, AT ANY TIME WITHOUT NOTICE. THE MATERIALS OR SERVICES AT THIS SITE MAY BE  OUT OF DATE, AND WE MAKE NO COMMITMENT TO UPDATE SUCH MATERIALS OR SERVICES.</p>
        <p>THE  USE OF THE SERVICES OR THE DOWNLOADING OR OTHER ACQUISITION OF ANY MATERIALS  THROUGH THIS SITE IS DONE AT YOUR OWN DISCRETION AND RISK AND WITH YOUR  AGREEMENT THAT YOU WILL BE SOLELY RESPONSIBLE FOR ANY DAMAGE TO YOUR PHONE,  TABLET, OR COMPUTER SYSTEM OR LOSS OF DATA THAT RESULTS FROM SUCH ACTIVITIES.</p>
        <p>Through  your use of the site, you may have the opportunities to engage in commercial  transactions with other users and vendors.  You acknowledge that all transactions relating to any merchandise or  services offered by any party, including, but not limited to the purchase  terms, payment terms, warranties, guarantees, maintenance and delivery terms  relating to such transactions, are agreed to solely between the seller or  purchaser of such merchandise and services and you. WE MAKE NO WARRANTY REGARDING ANY  TRANSACTIONS EXECUTED THROUGH, OR IN CONNECTION WITH THIS SITE, AND YOU  UNDERSTAND AND AGREE THAT SUCH TRANSACTIONS ARE CONDUCTED ENTIRELY AT YOUR OWN  RISK. ANY WARRANTY THAT IS PROVIDED IN  CONNECTION WITH ANY PRODUCTS, SERVICES, MATERIALS, OR INFORMATION AVAILABLE ON  OR THROUGH THIS SITE FROM A THIRD PARTY IS PROVIDED SOLELY BY SUCH THIRD PARTY,  AND NOT BY US OR ANY OTHER OF OUR AFFILIATES.</p>
        <p>Before  purchasing products and services on or through this site, review our Sales Terms  and Conditions, which are incorporated by reference into these Terms of Use.</p>
        <p>Content  available through this site may represent the opinions and judgments of an  information provider, site user, or other person or entity not connected with EmYa  Technologies LLC. We do not endorse, nor  are we responsible for the accuracy or reliability of, any opinion, advice, or  statement made by anyone other than an authorized EmYa Technologies LLC  spokesperson speaking in his/her official capacity. Please refer to the specific editorial  policies posted on various sections of this site for further information, which  policies are incorporated by reference into these Terms of Use.</p>
        <p>SOME  STATES OR JURISDICTIONS DO NOT ALLOW THE EXCLUSION OF CERTAIN WARRANTIES, SO  SOME OF THE ABOVE LIMITATIONS MAY NOT APPLY TO YOU.</p>
        <p><strong>11.Limitation  of Liability</strong></p>
        <p>Your  exclusive remedy and our entire liability, if any, for any claims arising out  of these Terms of Use and your use of this site shall be limited to the amount  you paid us for the services on the site during the one (1) month period before  the act giving rise to the liability.</p>
        <p>IN NO  EVENT SHALL WE OR OUR AFFILIATES BE LIABLE TO YOU OR ANY THIRD PARTY FOR ANY  SPECIAL, PUNITIVE, INCIDENTAL, INDIRECT OR CONSEQUENTIAL DAMAGES OF ANY KIND,  OR ANY DAMAGES WHATSOEVER, INCLUDING, WITHOUT LIMITATION, THOSE RESULTING FROM  LOSS OF USE, DATA OR PROFITS, WHETHER OR NOT WE HAVE BEEN ADVISED OF THE  POSSIBILITY OF SUCH DAMAGES, AND ON ANY THEORY OF LIABILITY, ARISING OUT OF OR  IN CONNECTION WITH THE USE OF THIS SITE OR OF ANY WEB SITE REFERENCED OR LINKED  TO FROM THIS SITE.</p>
        <p>FURTHER,  WE SHALL NOT BE LIABLE IN ANY WAY FOR THIRD PARTY GOODS AND SERVICES OFFERED  THROUGH THIS SITE OR FOR ASSISTANCE IN CONDUCTING COMMERCIAL TRANSACTIONS  THROUGH THIS SITE, INCLUDING WITHOUT LIMITATION THE PROCESSING OF ORDERS.</p>
        <p>SOME  JURISDICTIONS PROHIBIT THE EXCLUSION OR LIMITATION OF LIABILITY FOR  CONSEQUENTIAL OR INCIDENTAL DAMAGES, SO THE ABOVE LIMITATIONS MAY NOT APPLY TO  YOU.</p>
        <p><strong>12.Indemnification</strong></p>
        <p>Upon  a request by us, you agree to defend, indemnify, and hold us and our Affiliates  harmless from all liabilities, claims, and expenses, including attorney's fees  that arise from your use or misuse of this site. We reserve the right, at our own expense, to  assume the exclusive defense and control of any matter otherwise subject to  indemnification by you, in which event you will cooperate with us in asserting  any available defenses.</p>
        <p><strong>13.Participation  in Promotions</strong></p>
        <p>From  time to time, this site may include advertisements offered by third  parties. You may enter into  correspondence with or participate in promotions of the advertisers showing  their products on this site. Any such  correspondence or promotions, including the delivery of and the payment for  goods and services, and any other terms, conditions, warranties or  representations associated with such correspondence or promotions, are solely  between you and the advertiser. We  assume no liability, obligation or responsibility for any part of any such  correspondence or promotion.</p>
        <p><strong>14.Use  of Site and Storage of Material</strong></p>
        <p>You  acknowledge that we may establish general practices and limits concerning use  of the services available on our site, including without limitation the maximum  number of days that uploaded content will be retained on the site, the maximum  disk space that will be allotted or our servers on your behalf, and the maximum  number of times (and the maximum duration for which) you may access the  services in a given period of time. You  agree that we have no responsibility or liability for the deletion or failure  to store any content maintained or transmitted on or through this site. You acknowledge that we reserve the right to  log off accounts which have not paid a subscription fee that are inactive for  an extended period of time. You further  acknowledge that we reserve the right to change these general practices and limits  at any time, in our sole discretion, with or without notice.</p>
        <p>We  provide storage space and access for material through our site. For purposes of these Terms of Use,  &quot;material&quot; refers to all forms of communication that we may allow,  including narrative descriptions, graphics (including photographs,  illustrations, images, drawings, logos), executable programs, video recordings,  and audio recordings. You may not use  this site to publish material that we determine, at our sole discretion, to be  unlawful, indecent, or objectionable, or which violates the restrictions described  in &quot;Your Conduct on the Site&quot; above.  We will not routinely monitor the contents of your online  portfolio. You are solely responsible  for any information contained in your online portfolios. However, if complaints are received regarding  language, content, or graphics contained in your online portfolio, we may, at  our sole discretion, remove the images hosted on our servers and terminate your  Web hosting service. We may also suspend  the account, restrict access to it, or remove content from it if necessary or  appropriate.</p>
        <p>The  accounts of our users operate on shared resources. Excessive use or abuse of these shared  network resources by one user may have a negative impact on all other  users. Misuse of network resources in a  manner that impairs network performance, including excessive consumption of CPU  time, memory, disk space, and session time, is prohibited and may result in  termination of your account or limitation of your activities.</p>
        <p>This  site is not designed or intended to be used as a disaster recovery facility or  as an emergency data storage facility.  Although we take reasonable precautions to preserve and protect the  material you upload to the site, you should not rely on the site as your only  storage facility. You should preserve  backup copies of any digital data, information or other materials that you have  uploaded. You agree not to hold us for  any damage to, any deletion of or any failure to store your files, data or  Registration Data.<strong> </strong>Additionally, EmYa  Technologies LLC will retain bid information, however, such use will strictly  be used in order to collect trending data on pricing for each service sourced  through <a href="http://www.boxhopp.com">www.boxhopp.com</a>. </p>
        <p><strong>15.Security  and Password</strong></p>
        <p>You  are solely responsible for maintaining the confidentiality of your password and  account and for any and all statements made and acts or omissions that occur  through the use of your password and account, including any mail sent and any  charges incurred. Therefore, you must  take steps to ensure that others do not gain access to your password and  account. Our personnel will never ask  you for your password. You may not  transfer or share your account with anyone, and we reserve the right to  immediately terminate your account in the event of any unauthorized transfer or  sharing thereof.</p>
        <p><strong>16.Export  Controls</strong></p>
        <p>Software  available on or through this site is subject to United States Export  Controls. No software from this site may  be downloaded or exported (a) into (or to a resident of) Cuba, Iraq, Libya,  North Korea, Iran, Syria, or any other country which the United States has  embargoed goods; or (b) anyone on the United States Treasury Department's list  of Specially Designated Nationals or the United States Commerce Department's  Table of Deny Orders. By downloading or  using the software, you represent and warrant that you are not located in,  under the control of, or a national or resident of any such country or on any  such list.</p>
        <p>&nbsp;</p>
        <p><strong>17.International  Use</strong></p>
        <p>Although  this site may be accessible worldwide, we make no representation that materials  on this site are appropriate or available for use in locations outside the  United States, and accessing them from territories where their contents are  illegal is prohibited. Those who choose  to access this site from other locations do so on their own initiative and are  responsible for compliance with local laws.  Any offer for any product, service, and/or information made in  connection with this site is void where prohibited.</p>
        <p><strong>18.Termination  of Use</strong></p>
        <p>You  agree that we may, in our sole discretion, terminate or suspend your access to  all or part of the site with or without notice and for any reason, including,  without limitation, breach of these Terms of Use. Any suspected fraudulent, abusive or illegal  activity may be grounds for terminating your relationship and may be referred  to appropriate law enforcement authorities.</p>
        <p>Upon  termination or suspension, regardless of the reasons therefore, your right to  use the services available on this site immediately ceases, and you acknowledge  and agree that we may immediately deactivate or delete your account and all  related information and files in your account and/or bar any further access to  such files or this site. We shall not be  liable to you or any third party for any claims or damages arising out of any  termination or suspension or any other actions taken by us in connection therewith. Sections 1, 4, 6-12, 14, and 18-20 of these  Terms of Use, as well as your liability for any unpaid fees, shall survive any  termination.</p>
        <p><strong>19.Governing  Law</strong></p>
        <p>This  site (excluding any linked sites) is controlled by us from our offices within  the State of Texas, United States of America.  It can be accessed from all 50 states, as well as from other countries  around the world. As each of these  places has laws that may differ from those of Texas, by accessing this site  both of us agree that the statutes and laws of the State of Texas, without  regard to the conflicts of laws principles thereof and the United Nations  Convention on the International Sales of Goods, will apply to all matters  relating to the use of this site and the purchase of products and services  available through this site. Each of us  agrees and hereby submits to the exclusive personal jurisdiction and venue of  the Superior Court of Travis County and the United States District Court for  the Western District of Texas with respect to such matters.</p>
        <p><strong>20.Notices</strong></p>
        <p>All  notices to a party shall be in writing and shall be made via e-mail. Notices to us must be sent to the attention of  Customer Service at <a href="mailto:Boxhoppteam@boxhopp.com">Boxhoppteam@boxhopp.com</a>. Notices to you may be sent either to the  e-mail address supplied for your account as part of your Registration  Data. In addition, we may broadcast  notices or messages through the site to inform you of changes to the site or  other matters of importance, and such broadcasts shall constitute notice to  you.</p>
        <p>Any  notices or communication under these Terms of Use will be deemed delivered to  the party receiving such communication (a) on the delivery date if delivered  personally to the party; (b) two business days after deposit with a commercial  overnight carrier, with written verification of receipt; (c) five business days  after the mailing date, if sent by US mail, return receipt requested; (d) on  the delivery date if transmitted by confirmed facsimile; or (e) on the delivery  date if transmitted by confirmed e-mail.</p>
        <p><strong>21.Entire  Agreement</strong></p>
        <p>These  terms and conditions constitute the entire agreement and understanding between  us concerning the subject matter hereof and supersedes all prior agreements and  understandings of the parties with respect thereto. These Terms of Use may NOT be altered,  supplemented, or amended by the use of any other document(s). Any attempt to alter, supplement or amend  this document or to enter an order for products or services which are subject  to additional or altered terms and conditions shall be null and void, unless  otherwise agreed to in a written agreement signed by you and us. To the extent that anything in or associated  with this site is in conflict or inconsistent with these Terms of Use, these  Terms of Use shall take precedence.</p>
        <p><strong>22.Miscellaneous</strong></p>
        <p>In  any action to enforce these Terms of Use, the prevailing party will be entitled  to costs and attorneys' fees. Any cause  of action brought by you against us or our Affiliates must be instituted with  one year after the cause of action arises or be deemed forever waived and  barred.</p>
        <p>You  may not assign your rights and obligations under these Terms of Use to any  party, and any purported attempt to do so shall be null and void. We are free to assign our rights and  obligations under these Terms of Use.</p>
        <p>You  agree not to sell, resell, reproduce, duplicate, copy or use for any commercial  purposes any portion of this site, or use of or access to this site.</p>
        <p>In  addition to any excuse provided by applicable law, we shall be excused from  liability for non-delivery or delay in delivery of products and services  available through our site arising from any event beyond our reasonable  control, whether or not foreseeable by either party, including but not limited  to, labor disturbance, war, fire, accident, adverse weather, inability to  secure transportation, governmental act or regulation, and other causes or  events beyond our reasonable control, whether or not similar to those which are  enumerated above.</p>
        <p>If  any part of these Terms of Use is held invalid or unenforceable, that portion  shall be construed in a manner consistent with applicable law to reflect, as  nearly as possible, the original intentions of the parties, and the remaining  portions shall remain in full force and effect.</p>
        <p>Any  failure by us to enforce or exercise any provision of these Terms of Use or  related rights shall not constitute a waiver of that right or provision.</p>
        <p><strong>23.Contact  Information</strong></p>
        <p>If  you notice that any user is violating these Terms of Use, please contact us at <a href="mailto:Boxhoppteam@boxhopp.com">Boxhoppteam@boxhopp.com</a> or call us at  214-282-6524.</p>
    </div>
</div>

<?php include 'inc/footer.inc'; ?>

<script src="_js/jquery/jquery.js"></script>
<script src="_js/jquery-ui/jquery-ui.js"></script>
<script src="_js/jquery-waypoints/waypoints.js"></script>
<script src="_js/validatejs/validate.js"></script>
<script src="js/jumpSlides.js"></script>
<script src="js/scripts.js"></script>
</body>