<div id="footer">
    <div class="row">
        <div class="box companyinfo">
            <h3>Company Info</h3>
            <ul>
                <li><a href="privacy-policy">Privacy Policy</a></li>
                <li><a href="term-of-use">Term of Use</a></li>
            </ul>
            <p>Copyright &copy; 2014 EmYa Technologies, All rights reserved.</p>
        </div>
        <div class="box contact">
            <h3>Contact</h3>
            <ul>
                <li>General Support: (330) 275-3645</li>
                <li>General Support: <a href="mailto:support@boxhopp.com">support@boxhopp.com</a></li>
                <li>Technical Support: <a href="mailto:boxhoppteam@boxhopp.com">boxhoppteam@boxhopp.com</a></li>
            </ul>
        </div>
        <div class="box socialmedia">
            <h3>Social Media</h3>
            <ul>
                <li><a href="https://www.facebook.com/BoxhoppApp" class="facebook"></a></li>
                <li><a href="https://twitter.com/boxhopp" class="twitter"></a></li>
            </ul>
        </div>
    </div>
</div>