<div id="nav" class="navbar navbar-fixed-top mainNavTop">
    <div class="container row">
        <div class="logo">
            <a href="index"></a>
        </div>
        <div class="navbar navMenu mainNav">
            <div class="menuToggle mobileOnly">
                <div class="toggleContainer">
                    <a href="#">Menu</a>
                </div>
            </div>
            <ul class="nav navbar-nav">
                <li><a href="index">Home</a></li>
                <li><a href="movers">Membership</a></li>
                <li><a href="pricing">Pricing</a></li>
                <li><a href="about">About</a></li>
                <li><a href="contact">Contact</a></li>
                <li><a href="blog">Blog</a></li>
                <li class="mobileOnly mobOnly"><a href="login">Login</a></li>
            </ul>
        </div>
        <div class="login">
            <a href="/backend">Login</a>
        </div>
    </div>
</div>